# Generated by Django 4.0.1 on 2022-01-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('SectionId', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subsections',
            fields=[
                ('SubsectionId', models.AutoField(primary_key=True, serialize=False)),
                ('SubsectionName', models.CharField(max_length=100)),
                ('Section', models.CharField(max_length=100)),
            ],
        ),
    ]
