# Generated by Django 4.0.1 on 2022-01-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='SectionName',
            new_name='SectionTitle',
        ),
        migrations.AddField(
            model_name='sections',
            name='Content',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='Parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskApp.sections'),
        ),
    ]
