# Generated by Django 4.0.1 on 2022-01-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0002_rename_sectionname_sections_sectiontitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sections',
            name='Book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskApp.books'),
        ),
    ]
