# Generated by Django 4.0.1 on 2022-01-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0003_books_sections_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='isParent',
            field=models.BooleanField(default=False),
        ),
    ]
