# Generated by Django 4.0.1 on 2022-01-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0004_sections_isparent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subsections',
        ),
        migrations.AlterField(
            model_name='sections',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsecs', related_query_name='subsecs', to='taskApp.sections'),
        ),
    ]
